### ISSUE TITLE
How to remove underline and change color of span?

### ISSUE THREAD

**Issue by sandeshlasnapure** [Saketme/Better-Link-Movement-Method#4]

**Comment by Saketme** [comment]
The library doesn't add any underline span to links. Can you please add a screenshot? The highlight color can be changed by using `android:textColorHighlight="@color/your_color"` on your TextView. If you're trying to change the color on all TextViews across your app, you can add a `textViewStyle` in your theme.

**Comment by sandeshlasnapure** [comment]
Thanks, did that and removed underline.

**Comment by SureshSc** [comment]
I am getting underline, attaching screen shot 


here is my code
` <TextView
            android:id="@+id/tvComments"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="@dimen/value_2"
            android:fontFamily="@font/muli_semibold"
            android:textColor="@color/medium_black"
            android:textSize="@dimen/value_sp_17"
            android:textColorHighlight="@color/transparent"
            android:lineSpacingExtra="2dp" />`

<img width="283" alt="screen shot 2019-02-14 at 11 06 24 am" src="https://user-images.githubusercontent.com/5052940/52765072-9fe6ea80-3048-11e9-834e-2fe1ecf4e135.png">

**Comment by saket** [comment]
I think that's the default styling used by TextView. You'll have to manually replace those spans if you want.

```kotlin
val text: Spannable = ...
    
val urlSpans: Array<URLSpan> = text.getSpans(0, text.length, URLSpan::class.java)
for (urlSpan in urlSpans) {
  val startIndex = text.getSpanStart(urlSpan)
  val endIndex = text.getSpanEnd(urlSpan)
  text.removeSpan(urlSpan)
  text.setSpan(CustomUrlSpan(), startIndex, endIndex, 0)
}
```

**Comment by SureshSc** [comment]
@saket didnt work out, URLSpan count is 0

**Comment by saket** [comment]
That's not possible. You should check your data flow to ensure you're getting the right `text`.

**Comment by saket** [comment]
Actually, pass `Any` (or `Object`  in Java) as the span type to debug what spans are present in your text.

**Comment by SureshSc** [comment]
> That's not possible. You should check your data flow to ensure you're getting the right `text`.

I am sure.

**Comment by saket** [comment]
URLs are only rendered when `URLSpan`s are present in the text. If you're seeing linkified text then it means that there are URLSpans present in the text. It's contradictory otherwise.
