### ISSUE TITLE
Not work at all

### ISSUE THREAD

**Issue by DanteAndroid** [Saketme/Better-Link-Movement-Method#44]
```
  BetterLinkMovementMethod.linkify(Linkify.ALL, textView).setOnLinkClickListener { textView, url ->
                    println("onLinkClick $url")
                    false
                }
  textView.text = "https://www.google.com"
```
Environment: Emulator API 30
Library: 2.2.0

**Comment by DanteAndroid** [comment]
Damn, I move the `setText` before the `linkify` and it works great. 
Sorry to bother.

**Comment by Mrjayy2323** [comment]
What who's this--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 8/23/21, 12:21 AM Dante ***@***.***> wrote:

   
  Damn, I move the setText before the linkify and it works great. Sorry to bother.
